before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - main: '.'
    binary: quicknote
    flags:
      - -v
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X github.com/ramseskamanda/quicknote/cmd.Version={{.Version}} -X github.com/ramseskamanda/quicknote/cmd.Commit={{.Commit}}

release:
  prerelease: auto

universal_binaries:
  - replace: true

brews:
  - name: quicknote
    homepage: https://github.com/ramseskamanda/quicknote
    repository:
      owner: ramseskamanda
      name: homebrew-tap
    commit_author:
      name: ramseskamanda
      email: ramses.kamanda@gmail.com

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'